spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:3306/cheongsanghoe
    username: root
    password: '0310'
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

oauth2:
  google:
    client-id:
    client-secret:

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace